# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  db_user: ${{ secrets.DB_USER }}
  db_password: ${{ secrets.DB_PASSWORD }}
  db_name: ${{ secrets.DB_NAME }}
  host: ${{ secrets.HOST }}
  port: ${{ secrets.PORT }}
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install Dependencies
        run: poetry install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: pip install poetry
      
      - name: Install Dependencies
        run: 
          poetry install

      - name: test_script
        run: poetry run pytest
  
  coverage:
    runs-on: ubuntu-latest
    needs: [build,test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        run: pip install poetry
      
      - name: Install Dependencies
        run: | 
            poetry install
      
      - name: code_coverage
        run: poetry run pytest --cov=database_connection --cov=test_database_connection
