# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  self.db_user: ${{ secrets.DB_USER }}
  self.db_password: ${{ secrets.DB_PASSWORD }}
  self.db_name: ${{ secrets.DB_NAME }}
  self.host: ${{ secrets.HOST }}
  self.port: ${{ secrets.PORT }}
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
      
    - name: Install Poetry
      run: pip install poetry
      
    - name: Install Dependencies
      run: poetry install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: pip install poetry
      
    - name: Install Dependencies
      run: 
        poetry install

    - name: test_script
      run: poetry run pytest tests/test_database_connection.py
  
  coverage:
    runs-on: ubuntu-latest
    needs: [build,test]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: pip install poetry
      
    - name: Install Dependencies
      run: | 
          poetry install
      
    - name: code_coverage
      run: poetry run pytest --cov=database_connection --cov=test_database_connection
